package lunmijo.java;

/**
 *
 * @author Lunmijo
 * @version 0.2
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form TestJFrame
     */
    public Calculator() {
        initComponents();
        radioButtonOn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroupIsButtonsActive = new javax.swing.ButtonGroup();
        mainTextField = new javax.swing.JTextField();
        radioButtonOn = new javax.swing.JRadioButton();
        radioButtonOff = new javax.swing.JRadioButton();
        buttonBackspace = new javax.swing.JButton();
        buttonClearTextField = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonSubstract = new javax.swing.JButton();
        buttonMultiple = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonAddDot = new javax.swing.JButton();
        buttonReturnResult = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        supportTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        mainTextField.setEditable(false);
        mainTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroupIsButtonsActive.add(radioButtonOn);
        radioButtonOn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioButtonOn.setText("ON");
        radioButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOnActionPerformed(evt);
            }
        });

        buttonGroupIsButtonsActive.add(radioButtonOff);
        radioButtonOff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioButtonOff.setText("OFF");
        radioButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOffActionPerformed(evt);
            }
        });

        buttonBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonBackspace.setText("<-");
        buttonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackspaceActionPerformed(evt);
            }
        });

        buttonClearTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonClearTextField.setText("C");
        buttonClearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearTextFieldActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonSubstract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSubstract.setText("-");
        buttonSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubstractActionPerformed(evt);
            }
        });

        buttonMultiple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonMultiple.setText("*");
        buttonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultipleActionPerformed(evt);
            }
        });

        button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonAddDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAddDot.setText(".");
        buttonAddDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddDotActionPerformed(evt);
            }
        });

        buttonReturnResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonReturnResult.setText("=");
        buttonReturnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnResultActionPerformed(evt);
            }
        });

        buttonDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDivide.setText("/ ");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        supportTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTextField)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radioButtonOn)
                            .addGap(65, 65, 65)
                            .addComponent(buttonClearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioButtonOff)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonAddDot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonReturnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(supportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(supportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonClearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonOff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddDot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReturnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>                        
public double firstValue, ans;
    public int calculation;
    private boolean isEmpty;
    public double secondValue;
    
    private void radioButtonOnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        enable();
    }                                             

    private void buttonClearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        mainTextField.setText("");
        supportTextField.setText("");
    }                                                    

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (supportTextField.getText() != "") {
            secondValue = Double.parseDouble(mainTextField.getText());
            supportTextField.setText(Double.toString(CalculatorOperations.result_of_ariphmetic_operations(calculation, firstValue, secondValue)));
        }
        firstValue = Double.parseDouble(mainTextField.getText());
        supportTextField.setText(mainTextField.getText() + "+");
        mainTextField.setText("");
        calculation = 1;
    }                                         

    private void buttonSubstractActionPerformed(java.awt.event.ActionEvent evt) {                                                
        firstValue = Double.parseDouble(mainTextField.getText());
        supportTextField.setText(mainTextField.getText() + "-");
        mainTextField.setText("");
        calculation = 2;
    }                                               

    private void buttonMultipleActionPerformed(java.awt.event.ActionEvent evt) {                                               
        firstValue = Double.parseDouble(mainTextField.getText());
        supportTextField.setText(mainTextField.getText() + "*");
        mainTextField.setText("");
        calculation = 3;
    }                                              

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {                                             
        firstValue = Double.parseDouble(mainTextField.getText());
        supportTextField.setText(mainTextField.getText() + "/");
        mainTextField.setText("");
        calculation = 4;
    }                                            

    private void buttonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int length = mainTextField.getText().length();
        int number = mainTextField.getText().length() -1;
        String store;
        if (length > 0) {
            StringBuilder back = new StringBuilder(mainTextField.getText());
            back.deleteCharAt(number);
            store = back.toString();
            mainTextField.setText(store);
            
        }
    }                                               

    private void radioButtonOffActionPerformed(java.awt.event.ActionEvent evt) {                                               
        disable();
    }                                              

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "1");
    }                                       

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "2");
    }                                       

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "3");
    }                                       

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "4");
    }                                       

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "5");
    }                                       

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "6");
    }                                       

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "7");
    }                                       

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "8");
    }                                       

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            supportTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "9");
    }                                       

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (!isEmpty) {
            mainTextField.setText("");
            isEmpty = true;
        }
        mainTextField.setText(mainTextField.getText() + "0");
    }                                       

    private void buttonAddDotActionPerformed(java.awt.event.ActionEvent evt) {                                             
        mainTextField.setText(mainTextField.getText() + ".");
    }                                            

    private void buttonReturnResultActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        secondValue = Double.parseDouble(mainTextField.getText());
        supportTextField.setText(supportTextField.getText() + mainTextField.getText() + "=");
        show_result();
        isEmpty = false;
    }                                                  
    
    
    public void show_result() {
        mainTextField.setText(Double.toString(CalculatorOperations.result_of_ariphmetic_operations(calculation, firstValue, secondValue)));
    }
    public void disable() {
        radioButtonOn.setEnabled(true);
        mainTextField.setEnabled(false);
        buttonBackspace.setEnabled(false);
        buttonClearTextField.setEnabled(false);
        buttonAdd.setEnabled(false);
        buttonSubstract.setEnabled(false);
        buttonMultiple.setEnabled(false);
        button7.setEnabled(false);
        button9.setEnabled(false);
        button8.setEnabled(false);
        button4.setEnabled(false);
        button5.setEnabled(false);
        button6.setEnabled(false);
        button1.setEnabled(false);
        button2.setEnabled(false);
        button3.setEnabled(false);
        buttonDivide.setEnabled(false);
        button0.setEnabled(false);
        buttonAddDot.setEnabled(false);
        buttonReturnResult.setEnabled(false);

    }
    public void enable() {
        radioButtonOn.setEnabled(false);
        mainTextField.setEnabled(true);
        buttonBackspace.setEnabled(true);
        buttonClearTextField.setEnabled(true);
        buttonAdd.setEnabled(true);
        buttonSubstract.setEnabled(true);
        buttonMultiple.setEnabled(true);
        button7.setEnabled(true);
        button9.setEnabled(true);
        button8.setEnabled(true);
        button4.setEnabled(true);
        button5.setEnabled(true);
        button6.setEnabled(true);
        button1.setEnabled(true);
        button2.setEnabled(true);
        button3.setEnabled(true);
        buttonDivide.setEnabled(true);
        button0.setEnabled(true);
        buttonAddDot.setEnabled(true);
        buttonReturnResult.setEnabled(true);

    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAddDot;
    private javax.swing.JButton buttonBackspace;
    private javax.swing.JButton buttonClearTextField;
    private javax.swing.JButton buttonDivide;
    private javax.swing.ButtonGroup buttonGroupIsButtonsActive;
    private javax.swing.JButton buttonMultiple;
    private javax.swing.JButton buttonReturnResult;
    private javax.swing.JButton buttonSubstract;
    private javax.swing.JTextField mainTextField;
    private javax.swing.JRadioButton radioButtonOff;
    private javax.swing.JRadioButton radioButtonOn;
    private javax.swing.JTextField supportTextField;
    // End of variables declaration                   
}
